max_width = 100
hard_tabs = false
newline_style = "Unix"
use_small_heuristics = "Max"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
normalize_comments = true
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
