# Use the Alpine Linux base image
FROM docker.io/alpine:3.18

# Set environment
ENV LANG=en_AU.UTF-8 \
    LC_ALL=en_AU.UTF-8 \
    CHARSET=UTF-8 \
    PATH="/root/.cargo/bin:/home/appuser/.cargo/bin:$PATH"

# Install necessary packages
RUN apk update && apk add --no-cache \
    build-base \
    git \
    gpg \
    gpg-agent \
    dropbear \
    dropbear-dbclient \
    dropbear-ssh \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* /var/tmp/*

# Add a user for non-root execution and create home directory
RUN adduser -D appuser -u 1000 -g 1000 appuser

# Set working directory
WORKDIR /home/appuser

# Switch to non-root user
USER appuser
